# Generated by Django 4.2.8 on 2024-08-07 13:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("timestamp", models.TextField()),
                ("student_id", models.TextField()),
                ("payment_id", models.TextField()),
                ("payment_amount", models.BigIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_id", models.BigIntegerField()),
                ("result", models.TextField()),
                ("previous_hash", models.CharField(max_length=256)),
                ("hash", models.CharField(max_length=256)),
                ("nonce", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_year", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.TextField()),
                ("course_name", models.TextField()),
                ("course_credit", models.IntegerField()),
                ("payment_amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseAllowedForRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_batch", models.IntegerField()),
                ("semester", models.BooleanField(blank=True)),
                ("status", models.BooleanField(blank=True)),
                (
                    "class_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.classyear"
                    ),
                ),
                ("course", models.ManyToManyField(to="app.course")),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_name", models.CharField(max_length=50)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.faculty"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment_VNPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                ("order_desc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "vnp_TransactionNo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vnp_ResponseCode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10)),
                ("student_name", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=5, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("home_town", models.CharField(max_length=50)),
                ("status", models.BooleanField(blank=True)),
                ("enrollment_batch", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StudyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_program_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TuitionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_amount", models.BigIntegerField()),
                ("course_credit", models.IntegerField()),
                ("status", models.BooleanField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "approved_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.approvedcourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
                ("enrollment_batch", models.IntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.faculty"
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.major"
                    ),
                ),
                (
                    "study_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.studyprogram",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.studentclass"
            ),
        ),
        migrations.CreateModel(
            name="RegistedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_batch", models.IntegerField()),
                ("semester", models.BooleanField(blank=True)),
                ("status", models.BooleanField(blank=True)),
                (
                    "class_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.classyear"
                    ),
                ),
                ("course", models.ManyToManyField(to="app.course")),
                (
                    "course_allowed_for_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.courseallowedforregistration",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherCollectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_name", models.CharField(max_length=100)),
                ("payment_amount", models.BigIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.faculty",
                    ),
                ),
                (
                    "study_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.studyprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherCollectionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=100, null=True)),
                ("payment_amount", models.BigIntegerField()),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "other_collection_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.othercollectionplan",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="major",
            name="study_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.studyprogram"
            ),
        ),
        migrations.AddField(
            model_name="courseallowedforregistration",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.major"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.major",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="study_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.studyprogram",
            ),
        ),
        migrations.CreateModel(
            name="CollectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_period", models.IntegerField()),
                ("payment_name", models.CharField(max_length=100)),
                ("status", models.BooleanField(blank=True, null=True)),
                ("payment_amount", models.BigIntegerField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.major"
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.year"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="approvedcourse",
            name="registed_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.registedcourse"
            ),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("student_id", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")], max_length=10
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
