# Generated by Django 4.2.8 on 2024-08-07 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="class_name",
            new_name="student_class",
        ),
    ]
