# Generated by Django 4.2.8 on 2024-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thietlapmuchocphi",
            name="tinhChat",
        ),
        migrations.AddField(
            model_name="blockchain",
            name="nonce",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
