# Generated by Django 4.2.8 on 2024-02-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_thietlapmuchocphi_tinhchat_blockchain_nonce"),
    ]

    operations = [
        migrations.CreateModel(
            name="HocPhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maHocPhan", models.TextField()),
                ("tenHocPhan", models.TextField()),
                ("soTinChi", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HocPhanDaDangKy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hocKy", models.BooleanField(blank=True)),
                (
                    "hocPhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hocphan"
                    ),
                ),
                (
                    "namHoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.namhoc"
                    ),
                ),
                (
                    "sinhVien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sinhvien"
                    ),
                ),
            ],
        ),
    ]
