# Generated by Django 4.2.8 on 2024-02-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_hocphan_hocphandadangky"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphan",
            name="soTien",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="hocphandadangky",
            name="hocPhan",
        ),
        migrations.CreateModel(
            name="HocPhanChoDangKy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hocKy", models.BooleanField(blank=True)),
                ("hocPhan", models.ManyToManyField(to="app.hocphan")),
                (
                    "namHoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.namhoc"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hocphandadangky",
            name="hocPhan",
            field=models.ManyToManyField(to="app.hocphan"),
        ),
    ]
