# Generated by Django 4.2.8 on 2024-02-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_hocphanchodangky_namnhaphoc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hocphanchodangky",
            name="nienKhoa",
        ),
        migrations.AddField(
            model_name="hocphanchodangky",
            name="namKhoa",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
