# Generated by Django 4.2.8 on 2024-02-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_hocphanchodangky_nienkhoa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="maSinhVien",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
