# Generated by Django 4.2.8 on 2024-02-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_customuser_masinhvien"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinhvien",
            name="namKhoa",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
