# Generated by Django 4.2.8 on 2024-02-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_sinhvien_namkhoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphandadangky",
            name="namKhoa",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
