# Generated by Django 4.2.8 on 2024-03-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_hocphandadangky_namkhoa"),
    ]

    operations = [
        migrations.CreateModel(
            name="HocPhanDuocXetDuyet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hocPhanDaDangKy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.hocphandadangky",
                    ),
                ),
            ],
        ),
    ]
