# Generated by Django 4.2.8 on 2024-03-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_hocphanduocxetduyet"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphandadangky",
            name="trangThai",
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
