# Generated by Django 4.2.8 on 2024-03-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_hocphandadangky_trangthai"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphandadangky",
            name="hocPhanChoDangKy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hocphanchodangky",
            ),
            preserve_default=False,
        ),
    ]
