# Generated by Django 4.2.8 on 2024-03-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_hocphandadangky_hocphanchodangky"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThanhToanHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soTien", models.BigIntegerField()),
                ("trangThai", models.BooleanField(blank=True)),
                ("thoiGian", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "hocPhanDuocXetDuyet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.hocphanduocxetduyet",
                    ),
                ),
            ],
        ),
    ]
