# Generated by Django 4.2.8 on 2024-03-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_thanhtoanhocphi"),
    ]

    operations = [
        migrations.AddField(
            model_name="thanhtoanhocphi",
            name="sinhVien",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.sinhvien",
            ),
            preserve_default=False,
        ),
    ]
