# Generated by Django 4.2.8 on 2024-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_thanhtoanhocphi_sinhvien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment_vnpay",
            name="order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
