# Generated by Django 4.2.8 on 2024-03-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_khoanthukhac_thanhtoankhoanthukhac_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="khoanthukhac",
            name="heDaoTao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hedaotao",
            ),
        ),
    ]
