# Generated by Django 4.2.8 on 2024-03-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_khoanthukhac_hedaotao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kehoachthu",
            name="khoanThu",
            field=models.CharField(max_length=100),
        ),
    ]
