# Generated by Django 4.2.8 on 2024-03-06 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_kehoachthu_khoanthu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DanhMucThuChi",
        ),
    ]
