# Generated by Django 4.2.8 on 2024-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_delete_danhmucthuchi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchain",
            name="noiDung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kehoachthu",
            name="noiDung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="khoanthukhac",
            name="noiDung",
            field=models.TextField(blank=True, null=True),
        ),
    ]
