# Generated by Django 4.2.8 on 2024-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_remove_thanhtoankhoanthukhac_ghichu"),
    ]

    operations = [
        migrations.AddField(
            model_name="lop",
            name="namKhoa",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
