# Generated by Django 4.2.8 on 2024-04-06 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_lop_namkhoa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lop",
            name="khoaHoc",
        ),
    ]
