# Generated by Django 4.2.8 on 2024-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_remove_lop_khoahoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinhvien",
            name="gioiTinh",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
