# Generated by Django 4.2.8 on 2024-04-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_sinhvien_gioitinh"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphan",
            name="nganhDaoTao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.nganhdaotao",
            ),
        ),
        migrations.AlterField(
            model_name="hedaotao",
            name="tenHeDaoTao",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="khoa",
            name="tenKhoa",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="khoahoc",
            name="namKhoaHoc",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="lop",
            name="lop",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="namhoc",
            name="namHoc",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="nganhdaotao",
            name="tenNganhDaoTao",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sinhvien",
            name="hoTen",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sinhvien",
            name="queQuan",
            field=models.CharField(max_length=50),
        ),
    ]
