# Generated by Django 4.2.8 on 2024-04-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_hocphan_nganhdaotao_alter_hedaotao_tenhedaotao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphan",
            name="heDaoTao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hedaotao",
            ),
        ),
    ]
