# Generated by Django 4.2.8 on 2024-04-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_alter_hocphan_nganhdaotao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hocphan",
            name="heDaoTao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.hedaotao",
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="nganhDaoTao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.nganhdaotao",
            ),
        ),
        migrations.AlterField(
            model_name="hocphanchodangky",
            name="namHoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.namhoc"
            ),
        ),
        migrations.AlterField(
            model_name="hocphanchodangky",
            name="nganhDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.nganhdaotao"
            ),
        ),
        migrations.AlterField(
            model_name="hocphandadangky",
            name="hocPhanChoDangKy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.hocphanchodangky"
            ),
        ),
        migrations.AlterField(
            model_name="hocphandadangky",
            name="namHoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.namhoc"
            ),
        ),
        migrations.AlterField(
            model_name="hocphandadangky",
            name="sinhVien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.sinhvien"
            ),
        ),
        migrations.AlterField(
            model_name="hocphanduocxetduyet",
            name="hocPhanDaDangKy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.hocphandadangky"
            ),
        ),
        migrations.AlterField(
            model_name="kehoachthu",
            name="khoaHoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.khoahoc"
            ),
        ),
        migrations.AlterField(
            model_name="kehoachthu",
            name="nganhDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.nganhdaotao"
            ),
        ),
        migrations.AlterField(
            model_name="khoanthukhac",
            name="heDaoTao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.hedaotao",
            ),
        ),
        migrations.AlterField(
            model_name="khoanthukhac",
            name="khoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.khoa",
            ),
        ),
        migrations.AlterField(
            model_name="lop",
            name="heDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.hedaotao"
            ),
        ),
        migrations.AlterField(
            model_name="lop",
            name="khoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.khoa"
            ),
        ),
        migrations.AlterField(
            model_name="lop",
            name="nganhDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.nganhdaotao"
            ),
        ),
        migrations.AlterField(
            model_name="nganhdaotao",
            name="heDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.hedaotao"
            ),
        ),
        migrations.AlterField(
            model_name="nganhdaotao",
            name="khoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.khoa"
            ),
        ),
        migrations.AlterField(
            model_name="sinhvien",
            name="lop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.lop"
            ),
        ),
        migrations.AlterField(
            model_name="thanhtoanhocphi",
            name="hocPhanDuocXetDuyet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="app.hocphanduocxetduyet",
            ),
        ),
        migrations.AlterField(
            model_name="thanhtoanhocphi",
            name="sinhVien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.sinhvien"
            ),
        ),
        migrations.AlterField(
            model_name="thanhtoankhoanthukhac",
            name="khoanThuKhac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.khoanthukhac"
            ),
        ),
        migrations.AlterField(
            model_name="thanhtoankhoanthukhac",
            name="sinhVien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.sinhvien"
            ),
        ),
    ]
